/* ==========================================================================
   DATA STORES (TAHAP 1)
   ========================================================================== */
const ALPHABET_DATA = [
  { char: 'A', name: 'Apel', emoji: '🍎', phonetic: '/a · pel/' },
  { char: 'B', name: 'Bebek', emoji: '🦆', phonetic: '/be · bek/' },
  { char: 'C', name: 'Ceri', emoji: '🍒', phonetic: '/ce · ri/' },
  { char: 'D', name: 'Domba', emoji: '🐑', phonetic: '/dom · ba/' },
  { char: 'E', name: 'Elang', emoji: '🦅', phonetic: '/e · lang/' },
  { char: 'F', name: 'Flamingo', emoji: '🦩', phonetic: '/fla · ming · go/' },
  { char: 'G', name: 'Gajah', emoji: '🐘', phonetic: '/ga · jah/' },
  { char: 'H', name: 'Harimau', emoji: '🐯', phonetic: '/ha · ri · mau/' },
  { char: 'I', name: 'Ikan', emoji: '🐟', phonetic: '/i · kan/' },
  { char: 'J', name: 'Jeruk', emoji: '🍊', phonetic: '/je · ruk/' },
  { char: 'K', name: 'Kucing', emoji: '🐱', phonetic: '/ku · cing/' },
  { char: 'L', name: 'Lumba-lumba', emoji: '🐬', phonetic: '/lum · ba/' },
  { char: 'M', name: 'Monyet', emoji: '🐵', phonetic: '/mo · nyet/' },
  { char: 'N', name: 'Nanas', emoji: '🍍', phonetic: '/na · nas/' },
  { char: 'O', name: 'Orangutan', emoji: '🦧', phonetic: '/o · rang · u · tan/' },
  { char: 'P', name: 'Paus', emoji: '🐳', phonetic: '/pa · us/' },
  { char: 'Q', name: 'Quran', emoji: '📖', phonetic: '/qur · an/' },
  { char: 'R', name: 'Rusa', emoji: '🦌', phonetic: '/ru · sa/' },
  { char: 'S', name: 'Sapi', emoji: '🐮', phonetic: '/sa · pi/' },
  { char: 'T', name: 'Tupai', emoji: '🐿️', phonetic: '/tu · pai/' },
  { char: 'U', name: 'Unta', emoji: '🐫', phonetic: '/un · ta/' },
  { char: 'V', name: 'Vas', emoji: '🏺', phonetic: '/vas/' },
  { char: 'W', name: 'Wortel', emoji: '🥕', phonetic: '/wor · tel/' },
  { char: 'X', name: 'Xilofon', emoji: '🎼', phonetic: '/xi · lo · fon/' },
  { char: 'Y', name: 'Yoyo', emoji: '🪀', phonetic: '/yo · yo/' },
  { char: 'Z', name: 'Zebra', emoji: '🦓', phonetic: '/ze · bra/' }
];

// Minimal 40 suku kata dengan contoh kata konkret dan emoji akurat (Tahap 1 & Bug 1 Fix)
const SYLLABLE_DATA = [
  { syllable: 'BA', word: 'Baju', icon: '👕' },
  { syllable: 'BI', word: 'Bintang', icon: '⭐' },
  { syllable: 'BU', word: 'Buku', icon: '📚' },
  { syllable: 'BE', word: 'Bebek', icon: '🦆' },
  { syllable: 'BO', word: 'Bola', icon: '⚽' },
  { syllable: 'CA', word: 'Cacing', icon: '🪱' },
  { syllable: 'CI', word: 'Cincin', icon: '💍' },
  { syllable: 'CU', word: 'Cumi', icon: '🦑' },
  { syllable: 'CE', word: 'Ceri', icon: '🍒' },
  { syllable: 'CO', word: 'Coklat', icon: '🍫' },
  { syllable: 'DA', word: 'Dasi', icon: '👔' },
  { syllable: 'DI', word: 'Dinding', icon: '🧱' },
  { syllable: 'DU', word: 'Dunia', icon: '🌍' },
  { syllable: 'DE', word: 'Desa', icon: '🏡' },
  { syllable: 'DO', word: 'Domba', icon: '🐑' },
  { syllable: 'GA', word: 'Gajah', icon: '🐘' },
  { syllable: 'GI', word: 'Gigi', icon: '🦷' },
  { syllable: 'GU', word: 'Gurita', icon: '🐙' },
  { syllable: 'GE', word: 'Gelas', icon: '🥃' },
  { syllable: 'GO', word: 'Gorila', icon: '🦍' },
  { syllable: 'HA', word: 'Harimau', icon: '🐯' },
  { syllable: 'HI', word: 'Hiu', icon: '🦈' },
  { syllable: 'HU', word: 'Hujan', icon: '🌧️' },
  { syllable: 'HE', word: 'Helm', icon: '🪖' },
  { syllable: 'HO', word: 'Hotel', icon: '🏨' },
  { syllable: 'JA', word: 'Jam', icon: '⏰' },
  { syllable: 'JE', word: 'Jerapah', icon: '🦒' },
  { syllable: 'JI', word: 'Jip', icon: '🚙' },
  { syllable: 'JU', word: 'Jus', icon: '🧃' },
  { syllable: 'JO', word: 'Joran', icon: '🎣' },
  { syllable: 'KA', word: 'Kaki', icon: '🦶' },
  { syllable: 'KI', word: 'Kipas', icon: '🪭' },
  { syllable: 'KU', word: 'Kuda', icon: '🐴' },
  { syllable: 'KE', word: 'Keju', icon: '🧀' },
  { syllable: 'KO', word: 'Kopi', icon: '☕' },
  { syllable: 'LA', word: 'Labu', icon: '🎃' },
  { syllable: 'LI', word: 'Lilin', icon: '🕯️' },
  { syllable: 'LU', word: 'Lumba', icon: '🐬' },
  { syllable: 'LE', word: 'Lebah', icon: '🐝' },
  { syllable: 'LO', word: 'Loker', icon: '🗄️' },
  { syllable: 'MA', word: 'Mata', icon: '👀' },
  { syllable: 'MI', word: 'Mie', icon: '🍜' },
  { syllable: 'MU', word: 'Mulut', icon: '👄' },
  { syllable: 'ME', word: 'Melon', icon: '🍈' },
  { syllable: 'MO', word: 'Mobil', icon: '🚗' },
  { syllable: 'NA', word: 'Nasi', icon: '🍚' },
  { syllable: 'NI', word: 'Ninja', icon: '🥷' },
  { syllable: 'NU', word: 'Nuri', icon: '🦜' },
  { syllable: 'NE', word: 'Nenek', icon: '👵' },
  { syllable: 'PA', word: 'Palu', icon: '🔨' },
  { syllable: 'PI', word: 'Pita', icon: '🎀' },
  { syllable: 'PU', word: 'Pulau', icon: '🏝️' },
  { syllable: 'PE', word: 'Pensil', icon: '✏️' },
  { syllable: 'PO', word: 'Pohon', icon: '🌳' },
  { syllable: 'RA', word: 'Raja', icon: '👑' },
  { syllable: 'RI', word: 'Rias', icon: '💄' },
  { syllable: 'RU', word: 'Rusa', icon: '🦌' },
  { syllable: 'RO', word: 'Roti', icon: '🍞' },
  { syllable: 'SA', word: 'Sapi', icon: '🐮' },
  { syllable: 'SI', word: 'Singa', icon: '🦁' },
  { syllable: 'SU', word: 'Susu', icon: '🥛' },
  { syllable: 'SE', word: 'Sepatu', icon: '👟' },
  { syllable: 'SO', word: 'Sofa', icon: '🛋️' },
  { syllable: 'TA', word: 'Tali', icon: '🪢' },
  { syllable: 'TI', word: 'Tikus', icon: '🐭' },
  { syllable: 'TU', word: 'Tupai', icon: '🐿️' },
  { syllable: 'TE', word: 'Telinga', icon: '👂' },
  { syllable: 'TO', word: 'Topi', icon: '🧢' },
  { syllable: 'WA', word: 'Wajan', icon: '🍳' },
  { syllable: 'WO', word: 'Wortel', icon: '🥕' },
  { syllable: 'YO', word: 'Yoyo', icon: '🪀' },
  { syllable: 'YU', word: 'Yuyu', icon: '🦀' }
];

// Minimal 40 kata 4-huruf konkret (panjang tepat 4 karakter)
const WORDS_4 = [
  { word: 'BAJU', emoji: '👕' },
  { word: 'BOLA', emoji: '⚽' },
  { word: 'BUKU', emoji: '📚' },
  { word: 'BUSA', emoji: '🫧' },
  { word: 'BATA', emoji: '🧱' },
  { word: 'BAYI', emoji: '👶' },
  { word: 'BESI', emoji: '⛓️' },
  { word: 'BUMI', emoji: '🌍' },
  { word: 'DASI', emoji: '👔' },
  { word: 'PAUS', emoji: '🐳' },
  { word: 'GIGI', emoji: '🦷' },
  { word: 'GULA', emoji: '🍬' },
  { word: 'GURU', emoji: '🧑‍🏫' },
  { word: 'IKAN', emoji: '🐟' },
  { word: 'KAKI', emoji: '🦶' },
  { word: 'KOPI', emoji: '☕' },
  { word: 'KUDA', emoji: '🐴' },
  { word: 'KERA', emoji: '🐒' },
  { word: 'MADU', emoji: '🍯' },
  { word: 'KIWI', emoji: '🥝' },
  { word: 'LABU', emoji: '🎃' },
  { word: 'LAUT', emoji: '🌊' },
  { word: 'MATA', emoji: '👀' },
  { word: 'SOFA', emoji: '🛋️' },
  { word: 'NAGA', emoji: '🐉' },
  { word: 'NASI', emoji: '🍚' },
  { word: 'PALU', emoji: '🔨' },
  { word: 'PENA', emoji: '🖋️' },
  { word: 'PITA', emoji: '🎀' },
  { word: 'KURA', emoji: '🐢' },
  { word: 'PETA', emoji: '🗺️' },
  { word: 'PADI', emoji: '🌾' },
  { word: 'PARU', emoji: '🫁' },
  { word: 'ROTI', emoji: '🍞' },
  { word: 'RUSA', emoji: '🦌' },
  { word: 'SAPI', emoji: '🐮' },
  { word: 'SAPU', emoji: '🧹' },
  { word: 'SUSU', emoji: '🥛' },
  { word: 'TOPI', emoji: '🧢' },
  { word: 'TALI', emoji: '🪢' },
  { word: 'ULAR', emoji: '🐍' },
  { word: 'AWAN', emoji: '☁️' },
  { word: 'APEL', emoji: '🍎' },
  { word: 'AYAM', emoji: '🐔' },
  { word: 'UNTA', emoji: '🐫' },
  { word: 'DAUN', emoji: '🍃' },
  { word: 'RODA', emoji: '🛞' },
  { word: 'DADU', emoji: '🎲' },
  { word: 'OBAT', emoji: '💊' },
  { word: 'OTAK', emoji: '🧠' },
  { word: 'KADO', emoji: '🎁' },
  { word: 'PIZA', emoji: '🍕' },
  { word: 'KEJU', emoji: '🧀' },
  { word: 'TEKO', emoji: '🫖' },
  { word: 'GAUN', emoji: '👗' },
  { word: 'KUKU', emoji: '💅' },
  { word: 'ALIS', emoji: '🤨' },
  { word: 'MAIN', emoji: '🎮' },
  { word: 'GOLF', emoji: '⛳' },
  { word: 'KRAN', emoji: '🚰' },
  { word: 'ALAM', emoji: '🏞️' },
  { word: 'KOTA', emoji: '🏙️' },
  { word: 'DESA', emoji: '🏡' },
  { word: 'TRUK', emoji: '🚛' },
  { word: 'TREM', emoji: '🚋' },
  { word: 'KAYU', emoji: '🪵' },
  { word: 'BATU', emoji: '🪨' },
  { word: 'TISU', emoji: '🧻' },
  { word: 'KAIN', emoji: '🧣' },
  { word: 'AYAH', emoji: '👨' },
  { word: 'KOKI', emoji: '🧑‍🍳' },
  { word: 'BUAH', emoji: '🍑' },
  { word: 'CERI', emoji: '🍒' },
  { word: 'SATE', emoji: '🍢' },
  { word: 'FOTO', emoji: '🖼️' },
  { word: 'DRUM', emoji: '🥁' },
  { word: 'TANG', emoji: '🗜️' },
  { word: 'KUAS', emoji: '🖌️' },
  { word: 'PAHA', emoji: '🍗' },
  { word: 'KOIN', emoji: '🪙' },
  { word: 'BANK', emoji: '🏦' },
  { word: 'TOKO', emoji: '🏪' },
  { word: 'TUGU', emoji: '🗼' },
  { word: 'PURI', emoji: '🏰' },
  { word: 'SODA', emoji: '🥤' },
  { word: 'SAUS', emoji: '🥫' },
  { word: 'SOTO', emoji: '🥣' },
  { word: 'LAGU', emoji: '🎵' },
  { word: 'NADA', emoji: '🎶' },
  { word: 'FILM', emoji: '🎞️' },
  { word: 'HARI', emoji: '☀️' },
  { word: 'SORE', emoji: '🌇' },
  { word: 'PAGI', emoji: '🌅' },
  { word: 'LUKA', emoji: '🩹' },
  { word: 'TARI', emoji: '💃' },
  { word: 'LARI', emoji: '🏃' },
  { word: 'DURI', emoji: '🌵' },
  { word: 'HELM', emoji: '🪖' }
];

// Minimal 40 kata 5-6 huruf konkret (panjang tepat 5 atau 6 karakter)
const WORDS_LONG = [
  { word: 'JERUK', emoji: '🍊' },
  { word: 'EMBER', emoji: '🪣' },
  { word: 'BUNGA', emoji: '🌸' },
  { word: 'GARPU', emoji: '🍴' },
  { word: 'DOMBA', emoji: '🐑' },
  { word: 'GAJAH', emoji: '🐘' },
  { word: 'BEBEK', emoji: '🦆' },
  { word: 'TIKUS', emoji: '🐭' },
  { word: 'KAPAL', emoji: '🚢' },
  { word: 'MOBIL', emoji: '🚗' },
  { word: 'KERIS', emoji: '🗡️' },
  { word: 'RUMAH', emoji: '🏠' },
  { word: 'POHON', emoji: '🌳' },
  { word: 'BULAN', emoji: '🌙' },
  { word: 'HUJAN', emoji: '🌧️' },
  { word: 'SINGA', emoji: '🦁' },
  { word: 'BALON', emoji: '🎈' },
  { word: 'PISAU', emoji: '🔪' },
  { word: 'BOTOL', emoji: '🍼' },
  { word: 'PINTU', emoji: '🚪' },
  { word: 'ELANG', emoji: '🦅' },
  { word: 'ZEBRA', emoji: '🦓' },
  { word: 'SEMUT', emoji: '🐜' },
  { word: 'NANAS', emoji: '🍍' },
  { word: 'TUPAI', emoji: '🐿️' },
  { word: 'PISANG', emoji: '🍌' },
  { word: 'MANGGA', emoji: '🥭' },
  { word: 'KELAPA', emoji: '🥥' },
  { word: 'PENSIL', emoji: '✏️' },
  { word: 'SEPATU', emoji: '👟' },
  { word: 'SENDOK', emoji: '🥄' },
  { word: 'PAYUNG', emoji: '☂️' },
  { word: 'KERBAU', emoji: '🐃' },
  { word: 'KUCING', emoji: '🐱' },
  { word: 'WORTEL', emoji: '🥕' },
  { word: 'KERTAS', emoji: '📄' },
  { word: 'SENDAL', emoji: '🩴' },
  { word: 'DOMPET', emoji: '👛' },
  { word: 'CINCIN', emoji: '💍' },
  { word: 'JAGUNG', emoji: '🌽' },
  { word: 'BURUNG', emoji: '🐦' },
  { word: 'KERETA', emoji: '🚆' },
  { word: 'BADAK', emoji: '🦏' },
  { word: 'PETIR', emoji: '⚡' },
  { word: 'GELAS', emoji: '🥃' },
  { word: 'ANGSA', emoji: '🦢' },
  { word: 'PANDA', emoji: '🐼' },
  { word: 'KOALA', emoji: '🐨' },
  { word: 'KATAK', emoji: '🐸' },
  { word: 'GORILA', emoji: '🦍' },
  { word: 'ANJING', emoji: '🐶' },
  { word: 'RUBAH', emoji: '🦊' },
  { word: 'BUAYA', emoji: '🐊' },
  { word: 'KADAL', emoji: '🦎' },
  { word: 'LEBAH', emoji: '🐝' },
  { word: 'SIPUT', emoji: '🐌' },
  { word: 'GURITA', emoji: '🐙' },
  { word: 'KERANG', emoji: '🐚' },
  { word: 'UDANG', emoji: '🦐' },
  { word: 'LUMBA', emoji: '🐬' },
  { word: 'MERAK', emoji: '🦚' },
  { word: 'KALKUN', emoji: '🦃' },
  { word: 'NYAMUK', emoji: '🦟' },
  { word: 'LALAT', emoji: '🪰' },
  { word: 'CACING', emoji: '🪱' },
  { word: 'KUMAN', emoji: '🦠' },
  { word: 'MAWAR', emoji: '🌹' },
  { word: 'MELATI', emoji: '🌼' },
  { word: 'JAMUR', emoji: '🍄' },
  { word: 'BAMBU', emoji: '🎋' },
  { word: 'LEMON', emoji: '🍋' },
  { word: 'MELON', emoji: '🍈' },
  { word: 'ANGGUR', emoji: '🍇' },
  { word: 'TOMAT', emoji: '🍅' },
  { word: 'TERONG', emoji: '🍆' },
  { word: 'BAWANG', emoji: '🧅' },
  { word: 'BAKSO', emoji: '🍲' },
  { word: 'KACANG', emoji: '🥜' },
  { word: 'SUSHI', emoji: '🍣' },
  { word: 'DONAT', emoji: '🍩' },
  { word: 'PERMEN', emoji: '🍬' },
  { word: 'ESKRIM', emoji: '🍦' },
  { word: 'CABAI', emoji: '🌶️' },
  { word: 'GARAM', emoji: '🧂' },
  { word: 'PANCI', emoji: '🥘' },
  { word: 'WAJAN', emoji: '🍳' },
  { word: 'SABUN', emoji: '🧼' },
  { word: 'SIKAT', emoji: '🪥' },
  { word: 'SISIR', emoji: '🪮' },
  { word: 'CERMIN', emoji: '🪞' },
  { word: 'KASUR', emoji: '🛏️' },
  { word: 'LAMPU', emoji: '💡' },
  { word: 'KIPAS', emoji: '🪭' },
  { word: 'RADIO', emoji: '📻' },
  { word: 'KAMERA', emoji: '📷' },
  { word: 'VIDEO', emoji: '📹' },
  { word: 'LAPTOP', emoji: '💻' },
  { word: 'MOUSE', emoji: '🖱️' },
  { word: 'KABEL', emoji: '🔌' },
  { word: 'GITAR', emoji: '🎸' },
  { word: 'PIANO', emoji: '🎹' },
  { word: 'BIOLA', emoji: '🎻' },
  { word: 'TAKSI', emoji: '🚕' },
  { word: 'SEPEDA', emoji: '🚲' },
  { word: 'ROKET', emoji: '🚀' },
  { word: 'POMPA', emoji: '⛽' },
  { word: 'PERAHU', emoji: '⛵' },
  { word: 'TENDA', emoji: '⛺' },
  { word: 'RANSEL', emoji: '🎒' },
  { word: 'JAKET', emoji: '🧥' },
  { word: 'KEMEJA', emoji: '🥼' },
  { word: 'SARUNG', emoji: '🧤' },
  { word: 'CELANA', emoji: '👖' },
  { word: 'KALUNG', emoji: '📿' },
  { word: 'RAKET', emoji: '🏸' },
  { word: 'SKATE', emoji: '🛹' },
  { word: 'TROFI', emoji: '🏆' },
  { word: 'MEDALI', emoji: '🥇' }
];

/* ==========================================================================
   ATURAN DOMAIN F & G: KELOMPOK HURUF TERIKAT & TIPE HURUF (KLARIFIKASI 1)
   ========================================================================== */
const VOWELS = ['A', 'E', 'I', 'O', 'U'];
const CONSONANTS = [
  'B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M',
  'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z'
];

const CONFUSING_GROUPS = [
  // Bentuk mirip:
  ['B', 'D', 'P', 'Q'],
  ['M', 'N', 'W'],
  ['U', 'V'],
  ['I', 'J', 'L'],
  ['F', 'T'],
  ['C', 'E'],
  ['G', 'Q', 'Y'],
  ['H', 'N'],
  // Bunyi mirip:
  ['S', 'Z'],
  ['F', 'V'],
  ['K', 'G'],
  ['T', 'D'],
  ['P', 'B'],
  ['M', 'N'],
  // Vokal:
  ['A', 'E', 'I', 'O', 'U']
];

